<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_manageResident</name>
   <tag></tag>
   <elementGuidId>6192f8c1-a0fe-4285-a41b-1cc93f4e7680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e57b61d-9f6a-425f-9136-13a59d11cb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>b7696b96-9053-4d4e-a631-18a01d1f4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/manage-resident</value>
      <webElementGuid>fe8c7af2-7ba0-4418-8603-5b8fe69cd655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manage-resident</value>
      <webElementGuid>7a383565-a365-4208-ae75-f0948dd536cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>96ed7e88-5563-48d3-a1e3-b1b12750030d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Resident</value>
      <webElementGuid>21ec0954-1405-4fc4-9797-ce71a2cf91c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-ps-mantis&quot;)/div[@class=&quot;ng-scroll-content&quot;]/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;nav coded-inner-navbar&quot;]/app-nav-group[1]/app-nav-item[1]/li[@class=&quot;nav-item active&quot;]/a[1]</value>
      <webElementGuid>7c00fe02-2bca-4882-8780-94f5c00bad00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item/li/a</value>
      <webElementGuid>428ff168-32ac-44a1-ab30-9f221fc12fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::a[1]</value>
      <webElementGuid>898b3e44-f3c5-4aa7-8cbf-6c2a33a65fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Employee'])[1]/preceding::a[1]</value>
      <webElementGuid>2923ea47-0ace-4740-ac76-dcd6066807f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manage-resident')]</value>
      <webElementGuid>dac059da-4ac2-40e3-bda9-1d0802b53ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>66533d12-7c40-4775-b948-f9d5e362cc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manage-resident' and (text() = 'Manage Resident' or . = 'Manage Resident')]</value>
      <webElementGuid>cb3b5caa-46d3-4a45-909f-1839b629de14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
