<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_manageEmployee</name>
   <tag></tag>
   <elementGuidId>94573cf6-ea78-4165-83cf-ffc79faeeee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[2]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.active > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f31f3782-7dd9-4e84-a828-03fcac2ce906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>0a9a3e6f-3a28-4568-b602-6e914cb65ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/manage-employee</value>
      <webElementGuid>109c692e-d936-477d-923a-0ac61648ef73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manage-employee</value>
      <webElementGuid>d5d23116-edb2-4991-97e2-e40413c450aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>084cd3a0-4902-47b1-b228-c5bb79d14bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Employee</value>
      <webElementGuid>1c0af933-1e50-44e0-a523-8bb957921840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-ps-mantis&quot;)/div[@class=&quot;ng-scroll-content&quot;]/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;nav coded-inner-navbar&quot;]/app-nav-group[1]/app-nav-item[2]/li[@class=&quot;nav-item active&quot;]/a[1]</value>
      <webElementGuid>d92a3438-be06-40a0-b13f-fc8c7889a084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[2]/li/a</value>
      <webElementGuid>f0dc41da-6e9d-474a-9ccc-cd34e63bbbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Resident'])[1]/following::a[1]</value>
      <webElementGuid>347b6736-eb41-4ee3-9149-f98e66ee32b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::a[2]</value>
      <webElementGuid>bc80aaad-eb18-4815-822c-efe9a970ecac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Apartment'])[1]/preceding::a[1]</value>
      <webElementGuid>fd0f68c2-f81d-4779-9460-0ae08d1fbb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manage-employee')]</value>
      <webElementGuid>da553a06-5835-4b80-8c2a-199869d99871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-nav-item[2]/li/a</value>
      <webElementGuid>6497d191-6d0d-4ee8-a9e2-18abbe1c531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manage-employee' and (text() = 'Manage Employee' or . = 'Manage Employee')]</value>
      <webElementGuid>9081500c-d123-4128-a6a8-14f2293dfd51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
