<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPhoneNumber</name>
   <tag></tag>
   <elementGuidId>003262da-f309-44ab-a753-a4e51429a893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43433223-7451-42eb-9d23-43c58dbac955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f906475-cdd8-4fd9-ad4e-ded1f1e310e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>4c255372-1446-4e64-b0fe-b09e4a6c3b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]{10}$</value>
      <webElementGuid>24065e4e-1081-4b4a-9f43-c66f697483c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>7a8761e4-1c22-4ffe-8863-263fc191a2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f130e6dd-a2e6-45a0-b747-8a8ff8f8e36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]{10}$</value>
      <webElementGuid>1e85d90c-f085-4c55-abf1-de78032b8785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>d8a5c249-1a6d-4cc2-8c66-ddba9b75460d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumber&quot;)</value>
      <webElementGuid>43f0d909-359b-472d-bc8f-9b4098438d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNumber']</value>
      <webElementGuid>3eaa6ed6-523c-4a35-a4e4-09eb54f9ce5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>1578981b-d01e-4812-aabf-d55f38243390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'phoneNumber' and @name = 'phoneNumber']</value>
      <webElementGuid>263dc9d2-18c8-493d-adb2-1ccc8e72c5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
