<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_manageEmployee</name>
   <tag></tag>
   <elementGuidId>34bd4cdc-8d50-4c4b-8e67-548c5e7c344a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[2]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.active > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8a47824-167a-4bb7-a689-c8f767acad72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>94696bb5-a59d-4de4-bc19-b9d7d0978db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/manage-employee</value>
      <webElementGuid>af1b8520-945a-4132-b043-4740f8258e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manage-employee</value>
      <webElementGuid>f2fde11e-7d85-4b86-b105-44df57321718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>c972f469-9673-4258-8cb6-7f10a5710923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Employee</value>
      <webElementGuid>6c6bb922-b8d3-48b2-84c9-4fa86aa648c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-ps-mantis&quot;)/div[@class=&quot;ng-scroll-content&quot;]/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;nav coded-inner-navbar&quot;]/app-nav-group[1]/app-nav-item[2]/li[@class=&quot;nav-item active&quot;]/a[1]</value>
      <webElementGuid>1727ff9c-b469-4c17-a3de-c47983834062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[2]/li/a</value>
      <webElementGuid>65734160-67d9-44e2-8135-83a14c9b610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Resident'])[1]/following::a[1]</value>
      <webElementGuid>1c125c50-cf8f-44c0-a3cf-c474a78418f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::a[2]</value>
      <webElementGuid>381ff394-7710-4f39-b8df-66167e201eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Apartment'])[1]/preceding::a[1]</value>
      <webElementGuid>9b0fe99a-e2fb-4ce6-8273-d33b7d72ea05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manage-employee')]</value>
      <webElementGuid>bff2e82d-b208-4c4b-8a7c-de70b304bf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-nav-item[2]/li/a</value>
      <webElementGuid>32fb29a1-f01d-4526-8349-445463ab9cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manage-employee' and (text() = 'Manage Employee' or . = 'Manage Employee')]</value>
      <webElementGuid>f5b35855-1cb5-489a-8f51-3ac28c9e447d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
