<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_manageReport</name>
   <tag></tag>
   <elementGuidId>6ffa433d-ab13-4e46-b509-6baa14334fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-nav-item:nth-of-type(5) > li.nav-item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[5]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fb183fa-89f6-4fc0-881f-59d4c1943738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>39b78fb0-eed5-4fab-9a66-36c232ff8534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/manage-report</value>
      <webElementGuid>5e428a49-d479-40c3-a6d9-f8f5d2ec9d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manage-report</value>
      <webElementGuid>8820e20a-ee59-4165-a3d6-0834e37bffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>d0407ba3-df05-4e2d-ac25-d28c9a4a084e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Report</value>
      <webElementGuid>58f12ceb-a118-49c2-8e25-f72525af9cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-ps-mantis&quot;)/div[@class=&quot;ng-scroll-content&quot;]/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;nav coded-inner-navbar&quot;]/app-nav-group[1]/app-nav-item[5]/li[@class=&quot;nav-item&quot;]/a[1]</value>
      <webElementGuid>8999c2a4-1b3e-440c-8258-86331c82d5ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[5]/li/a</value>
      <webElementGuid>d0831d3a-7fa4-4fc3-aa10-15518c799eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Bill'])[1]/following::a[1]</value>
      <webElementGuid>832f2ad8-336a-46c6-9152-5e1ec8351895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Apartment'])[1]/following::a[2]</value>
      <webElementGuid>4728aaba-8d75-4293-b961-f190064845df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[4]</value>
      <webElementGuid>12fe3822-a57b-4955-87f1-0a2334d1b5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manage-report')]</value>
      <webElementGuid>c6fc29db-3a2d-4d9a-9c65-5b3e108fd860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-nav-item[5]/li/a</value>
      <webElementGuid>95879753-3545-47d9-a62a-96d46532a362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manage-report' and (text() = 'Manage Report' or . = 'Manage Report')]</value>
      <webElementGuid>3683be54-f9dc-46d7-95cc-61048c7cd185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
