<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_manageBill</name>
   <tag></tag>
   <elementGuidId>64f0b645-cfe1-488a-be64-0a650bfe8ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-nav-item:nth-of-type(4) > li.nav-item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[4]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1397c2e2-f7d8-42f9-845e-15255cfe6b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>eed686a6-50f6-4758-bdc6-9f893f41b0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/manage-bill</value>
      <webElementGuid>b3501be1-67f8-459c-bdfc-879ba24426ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manage-bill</value>
      <webElementGuid>67c97ea1-52c8-47de-9391-052ab969a129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>be01bd45-0cbd-4ccd-ac4b-e467b67293a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Bill</value>
      <webElementGuid>b9de7dd1-0e1e-4d86-872a-a16c3cad041a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-ps-mantis&quot;)/div[@class=&quot;ng-scroll-content&quot;]/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;nav coded-inner-navbar&quot;]/app-nav-group[1]/app-nav-item[4]/li[@class=&quot;nav-item&quot;]/a[1]</value>
      <webElementGuid>8c15d8bf-de60-47f2-884c-6dd912a0add9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-scrollbar[@id='nav-ps-mantis']/div/div/ul/app-nav-group/app-nav-item[4]/li/a</value>
      <webElementGuid>e63e8364-00fd-4d64-853b-667b98bd8ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Apartment'])[1]/following::a[1]</value>
      <webElementGuid>0ff03dcb-3bb9-4732-b9cc-3c36f1a6ae45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Employee'])[1]/following::a[2]</value>
      <webElementGuid>347df832-c740-4f7d-8143-867304da58aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Report'])[1]/preceding::a[1]</value>
      <webElementGuid>40d2ec8a-99fa-45a0-916e-55ca4a525983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manage-bill')]</value>
      <webElementGuid>44e65259-9127-4673-8dc7-f75c71c3f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-nav-item[4]/li/a</value>
      <webElementGuid>798fd29b-b2c0-4176-ae0b-486a17bf4b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manage-bill' and (text() = 'Manage Bill' or . = 'Manage Bill')]</value>
      <webElementGuid>886464ce-8f08-4753-86c4-62f415857f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
