<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectResident</name>
   <tag></tag>
   <elementGuidId>dec3662b-497e-49ec-bea5-fdfb748a484d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#residentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='residentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83827406-dc40-4a44-81ac-74d5141c2a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>9e62ebf1-8c6b-44ee-b584-3a6dad41ab14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>a616d3c7-28db-4999-9cad-62715150a299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cb366bfd-b315-42da-b7ad-848e529ea4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>71e7559d-c4cb-4be1-8a05-be26b3625a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh</value>
      <webElementGuid>5d6672d5-300d-46e1-859c-110bdbad6d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residentName&quot;)</value>
      <webElementGuid>02135b32-e1c7-4d69-bb14-345e97a8e403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='residentName']</value>
      <webElementGuid>a89128ca-67a1-46ae-9d1a-496e7f502782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/following::select[1]</value>
      <webElementGuid>2bbbce04-b9f0-4f0e-b034-6a72d7aa6b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of apartment'])[1]/following::select[2]</value>
      <webElementGuid>c35635b1-0c8e-4f32-9597-f51f8deeeda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::select[1]</value>
      <webElementGuid>a9491dfd-b563-40c6-a9de-9a6c2cf56f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number electric'])[1]/preceding::select[1]</value>
      <webElementGuid>dc6238d1-daeb-4da2-86cb-b73b2e6a5fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>91f0a630-a5f7-48c6-909a-47334ab69c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'residentName' and @id = 'residentName' and (text() = 'Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh' or . = 'Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh')]</value>
      <webElementGuid>b4f75662-9d7d-49e4-828c-9a20ddcbc264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
