<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectNumOfApart</name>
   <tag></tag>
   <elementGuidId>1cbc8086-3e6e-4975-a574-9ac147915112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfApartment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='numberOfApartment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a8a915b-26f8-43e1-84d0-9eae3cfc0a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>40dd4261-dbaf-48ea-8d40-56047f818bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>f4edcd9d-7e60-4195-9c48-4471698915f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b1e92105-9410-41ed-b79a-7874496c7552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>fdf2e4c9-5e79-4922-ab4a-35ad7c872383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Apartment 101  102  711  7  437  436 </value>
      <webElementGuid>66d89281-00ea-4ed7-8d9b-1deecac2e024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfApartment&quot;)</value>
      <webElementGuid>563a5858-03fa-4159-971e-cbcd51509fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='numberOfApartment']</value>
      <webElementGuid>76fc2145-0541-429a-b31a-7921d9ccdb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of apartment'])[1]/following::select[1]</value>
      <webElementGuid>130244dd-ce41-460e-90d5-fb7a156e221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Report'])[1]/following::select[1]</value>
      <webElementGuid>f3ac782e-74c8-4775-b9ab-6186214e7eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/preceding::select[1]</value>
      <webElementGuid>c3a76650-59e6-448f-a972-f99b284bd4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::select[2]</value>
      <webElementGuid>afeb013f-2b88-407d-9511-78c36957cfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>12ef1ebd-fe3a-438e-a19a-76667c71a9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'numberOfApartment' and @id = 'numberOfApartment' and (text() = 'Select Apartment 101  102  711  7  437  436 ' or . = 'Select Apartment 101  102  711  7  437  436 ')]</value>
      <webElementGuid>a8766853-bb93-4c97-a0de-863357e80f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
