<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNumElec</name>
   <tag></tag>
   <elementGuidId>964e7536-9821-427e-a6a6-903bd2567075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberElectric</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberElectric']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a6a074d-49ad-4fb5-9e40-2220fdff7c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97e27201-4116-4588-bdb9-4acf34a3f76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>426b9a98-5e7f-461c-8ce2-f7c519e01a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>x3500/Volt</value>
      <webElementGuid>0aa7929f-4a7f-496e-b6e4-5fe4d4520d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>1b2f2df4-9cf2-434c-af9b-ce96bde6f74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>55adb7bc-5c8c-4144-840d-0803301038db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>28a3313d-7d97-4ac3-aec7-f60e6e0dddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>a2d596f1-6b34-4104-a07a-0c4b05d30128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>f1de46cb-9b3a-42b9-b5bd-1345dca8313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberElectric&quot;)</value>
      <webElementGuid>5031e361-83fe-4076-83bb-9314c26ebb0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberElectric']</value>
      <webElementGuid>2a721f0b-3360-4f56-b879-0d9630e93ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>036bc8f2-1abf-47ab-9e8a-ae3f1116fdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'numberElectric' and @placeholder = 'x3500/Volt' and @name = 'numberElectric']</value>
      <webElementGuid>cd88936d-ca2b-4fe9-86d5-2e3031a0cddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
