<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtToiletMoney</name>
   <tag></tag>
   <elementGuidId>c0d4d377-92a3-4e28-8686-37a49a940167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toiletMoney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='toiletMoney']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb46d983-b05a-411d-865d-6cc5b5a1226b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a09a839a-a7cc-44bc-9efd-724a13a3d382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>f98fadc3-3893-435e-8ca5-161463b72d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>03a601bf-f760-4d42-8080-f784c6a1473f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>7c28bcb9-bc8a-43e8-816d-f267123b3733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6649b127-525c-4631-bb7f-8f69e6060776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>bbe3b19e-08b2-4684-9789-df60bc6a8339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>609b2a80-ddc7-4510-b69d-fbf6da0c376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toiletMoney&quot;)</value>
      <webElementGuid>50a9fa63-bb5b-4ce0-9733-58a1d8f0c242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='toiletMoney']</value>
      <webElementGuid>0d610965-ae0a-44a2-81f6-27b7fe8bfb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>5ad6e2ba-0bc4-4b2e-92a9-665a79a7f134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'toiletMoney' and @name = 'toiletMoney']</value>
      <webElementGuid>5a7d156a-727b-4ced-9fde-8d46f26c94bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
