<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectResident</name>
   <tag></tag>
   <elementGuidId>5d791e8f-5bd7-4333-af34-6fda7e9c0ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#residentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='residentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>32d4b824-c2d5-423c-9c78-af8f8186ec71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>77b0ae7f-f84d-4288-b0c0-0418900204a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>4ae015c6-ecf8-46bc-9d49-375d3b368c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e0ca2312-affa-4a85-924d-984fb66b28d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>e25da579-2b5b-4c2f-b981-c993756c1057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh </value>
      <webElementGuid>de0ab082-65de-4a10-930f-9a96c728f64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residentName&quot;)</value>
      <webElementGuid>1727bcf9-f090-462a-9ed4-9f0da018ff2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='residentName']</value>
      <webElementGuid>7eacd169-1ada-4393-b3b9-827eea04a75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/following::select[1]</value>
      <webElementGuid>87dcd513-4838-4b7a-bbab-b0976b13659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>5f3d27e9-3e2f-4fd1-a24a-1a864fb65076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>52834c9c-f11e-4b83-8546-7ef087a46376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CodedThemes'])[1]/preceding::select[1]</value>
      <webElementGuid>5aaea631-c19c-4169-b64d-b518b32e1847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>cc9a3611-e6f3-4046-9629-27a6e8aa0ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'residentName' and @id = 'residentName' and (text() = 'Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh ' or . = 'Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh ')]</value>
      <webElementGuid>1001e1cc-2cbe-4ff5-b198-c43c3460b771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
