<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectStatus</name>
   <tag></tag>
   <elementGuidId>dfdef782-970a-43a0-aa1b-3e6ecef48fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>21987ad4-5db1-4ff6-a0e3-ddb44a84e6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>395c3beb-a93a-487b-bf45-8e3c14c4a798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>b62e0a7b-335a-466d-8907-9ebd4f10d5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>77fa9273-1ae9-471f-b3db-1c8d9721cc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>0e277a9e-f64b-4539-8fd6-d3e949410f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StatusAvailableInAvailable</value>
      <webElementGuid>96f030c1-d6d9-4687-ac2c-ed2fbe005b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status&quot;)</value>
      <webElementGuid>df36fe1b-e086-4f67-8dca-8b44b1ae0892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status']</value>
      <webElementGuid>d0c97f34-43db-4756-a44b-0d4146a9a333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>66c06aa7-6c7c-467a-a47b-754a035aef2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of apartment'])[1]/following::select[1]</value>
      <webElementGuid>fe694aa6-2678-4cd4-bfdf-98a04d4798c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/preceding::select[1]</value>
      <webElementGuid>254cb928-0c86-461a-9acc-18b0a4eb83bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[2]</value>
      <webElementGuid>fbac9458-fbbb-4384-89c7-dbd6889ce142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>033c603a-07fe-4612-b833-b8d15ca1b464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status' and @id = 'status' and (text() = 'Select StatusAvailableInAvailable' or . = 'Select StatusAvailableInAvailable')]</value>
      <webElementGuid>0399c1ca-bd09-43cb-9fdb-4afc49b15f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
