<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>detail_delete_Bill</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dc183cc2-793f-4dae-a9fc-bff39052b0b1</testSuiteGuid>
   <testCaseLink>
      <guid>b8918158-8212-46fd-a29a-7f4762b424da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/login_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd6c50a4-f09d-48d8-95d9-cd7f77529634</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginData/loginSuccess</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dd6c50a4-f09d-48d8-95d9-cd7f77529634</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>12db6fb3-1f7d-4c3e-b791-410378a03fb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd6c50a4-f09d-48d8-95d9-cd7f77529634</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b04ce358-939e-449a-9a4d-5ce21093f005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd6c50a4-f09d-48d8-95d9-cd7f77529634</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedMsg</value>
         <variableId>7d9521c1-41c1-4924-978f-4eb62b4df9c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c07a107-54ec-43c0-a4d0-ca1db37f1e4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/bill/detail/bill_detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>800dd122-311b-4d05-af95-f94e8f6b8d67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb621432-f83f-4cc7-9cdc-b86fd9bb7472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e03805c3-8147-4ace-aff7-cc0a13605f5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e250f18a-1cd2-46e7-9263-c02440e08138</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86321637-0182-40bc-8c7f-c604c32da3a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cde3cc9f-ca1c-497b-904f-9c0060c5740e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac353c73-8a5f-4f9d-94e2-4dc076efb1e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2c68375-ab6b-42fa-b58d-c2bbeb4d9f98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/bill/delete/bill_delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ba50d47-af11-4099-9a40-a5bf9b1ad36a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8727de20-dea9-46d2-8954-bb11267ba820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74e819b1-7376-4a95-b1bd-551efebec6ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd9fd22-3e85-4cd2-abf2-11d8e3469d0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d8e02e-d932-4fb6-af3a-9402996721fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24b44873-3920-4a2e-a165-527644608221</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c517841c-b95b-44b1-856c-51f7ceac5447</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
