<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>add_Report</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a2ad4c3d-9427-45bd-b452-c923a8b8be3a</testSuiteGuid>
   <testCaseLink>
      <guid>e7a6f1ad-b15b-4b3e-ab45-84659f3e1934</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/login_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86b4131c-e1e8-49bc-a8a8-08ad0ace04b1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginData/loginSuccess</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>86b4131c-e1e8-49bc-a8a8-08ad0ace04b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>12db6fb3-1f7d-4c3e-b791-410378a03fb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86b4131c-e1e8-49bc-a8a8-08ad0ace04b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b04ce358-939e-449a-9a4d-5ce21093f005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86b4131c-e1e8-49bc-a8a8-08ad0ace04b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedMsg</value>
         <variableId>7d9521c1-41c1-4924-978f-4eb62b4df9c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c5a6bbd-61a7-4612-ae1c-4f670e61f680</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/report/add/report_add_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>73cfaba1-7171-4936-b4fc-95a020290028</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/report/add/add_Success</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>73cfaba1-7171-4936-b4fc-95a020290028</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nameReport</value>
         <variableId>7bc1fe05-1883-4a47-8e71-c2734fbda59c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>73cfaba1-7171-4936-b4fc-95a020290028</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>0ba9f3fa-4b7e-4905-ab29-aee35b11fb2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>73cfaba1-7171-4936-b4fc-95a020290028</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>content</value>
         <variableId>d17e4aa1-e9e7-4fc6-af24-b3c2332c96ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4369065e-7f75-4e66-9e16-5606979666b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/report/add/report_add_required</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7ffe06e-90c4-4cbc-a94f-737fbff060b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be82234c-ca7e-4c23-b14f-efeff75a0488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9901485-d8c7-4e67-a55c-4ecbda399a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67d3857a-2a88-4d7b-a717-f4dac3de1f4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41fbb947-a320-4a4f-8624-2827cf057561</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bd1f06a-ea36-4736-bb03-ab1b2eeecdeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c84ea67-0cab-4d52-8a5c-040b464d35c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
