<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>detail_delete_Report</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8642e2e2-7eff-4d3d-8b0f-a269b547d2a4</testSuiteGuid>
   <testCaseLink>
      <guid>2f553082-ecca-4870-b7d1-a8a67948cbf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/login_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>69d906ef-f339-4302-b23f-e77517a1ea34</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginData/loginSuccess</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>69d906ef-f339-4302-b23f-e77517a1ea34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>12db6fb3-1f7d-4c3e-b791-410378a03fb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69d906ef-f339-4302-b23f-e77517a1ea34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b04ce358-939e-449a-9a4d-5ce21093f005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69d906ef-f339-4302-b23f-e77517a1ea34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedMsg</value>
         <variableId>7d9521c1-41c1-4924-978f-4eb62b4df9c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7caf545f-cf4f-4b6d-9091-2000d788f599</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/report/detail/report_detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bf6fae7-b8de-4197-b275-c30799d67e35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a9c0586-43aa-4bd5-969f-d9952b1af58e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8645717e-b9e7-47b8-b4f0-15a7c83dc32f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f796d195-9b8f-4631-bdfe-877a546e91dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0e3eb7f-649a-4c3c-8c9d-25c7745e00fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0da3615-9ab6-47a7-8891-43d9cd01093d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc3d818d-95f1-4692-8051-516218b8f127</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a37f36a3-a9ec-4925-ac6d-2b8b997167cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/report/delete/report_delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2a9671-9fb7-49cb-b34b-a8ff7bbef798</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040ab45b-513d-4471-8cb6-f20168c238f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bef8483-3522-4ba8-9fff-79354d92be70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f950b91-a489-48bc-b428-7fbbb9abf89e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>074dd002-7a0e-49aa-b8a1-4e73dd2ba5c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2110804-ac21-4294-8058-302c5355163a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd248b48-7c67-40e8-8ae2-2aeb0c50673b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
