<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectResident</name>
   <tag></tag>
   <elementGuidId>f260cff4-e939-4e99-b9cc-7faa6b01eb11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#residentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='residentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d886899-7766-4271-92d4-537fd16fb0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>b4df8bb9-51e5-46fe-af75-7a4aa6b30fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>03ac15e8-3494-46cc-832a-7f281d328e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>09d087d5-d84c-43e2-9264-d70543231a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>2688384a-b68d-4779-8267-8b25368b3093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>Cao Thị T</value>
      <webElementGuid>28f518d8-3d37-4281-b1bd-2e0dad1d713a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh </value>
      <webElementGuid>b66ca4c3-a795-47f6-8af0-12e600614b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residentName&quot;)</value>
      <webElementGuid>21755732-2274-4de4-b604-280ef505c907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='residentName']</value>
      <webElementGuid>7908cc4b-cf38-405b-9b49-ad1d4f526220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/following::select[1]</value>
      <webElementGuid>c177b550-cefb-489d-b85e-f050d0b6bd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>cab5d81c-b0a7-47c5-8578-b0678b32ca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>254d9788-a047-4503-a807-89c210cb34aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CodedThemes'])[1]/preceding::select[1]</value>
      <webElementGuid>9b5cacef-b6a1-4837-a553-b6b39c2dd60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>5df7eaac-34f2-43f4-8ba6-09084ca3c662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'residentName' and @id = 'residentName' and (text() = 'Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh ' or . = 'Select Resident Nguyễn Văn A  Cao Thị T  Cao Văn C  tu  Bùi Chi  Lý Vũ  Lê Trang  Cao Dũng  Hồ Bình  Lê Linh ')]</value>
      <webElementGuid>f3fd7c8b-b131-4380-8a0e-81e533e57861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
