<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNumberOfApart</name>
   <tag></tag>
   <elementGuidId>dff34b5a-d005-4545-9c36-1abfb4258ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfApartment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfApartment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51d29b87-2759-48d2-8b69-192b93b6e9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b133e05-c798-45ac-bf22-7084c6952cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>bb5bfffe-1886-4f7b-b452-7f6a9024e592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8127dd12-63f4-4627-b56b-80f9dec6beb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>48038415-ce1e-411c-a159-712ebcc1678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>ad94c0e3-1072-4640-ad4e-4e900d1f54e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c8f347d4-b26b-4715-b48d-de0302d6e214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>6c8d2e7a-81db-47a0-9048-fff28bc46944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>202</value>
      <webElementGuid>61afc7a9-6921-4665-b184-23203c425764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfApartment&quot;)</value>
      <webElementGuid>74d6b981-a6d0-4580-a7b1-75bbc639fe56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfApartment']</value>
      <webElementGuid>6aa81fd0-02f0-47bc-86ae-2f0e4a502cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fe5074ad-3f9e-4267-9ce0-6818da7ad0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'numberOfApartment' and @name = 'numberOfApartment']</value>
      <webElementGuid>187c22d1-b38c-41f4-8143-be9b44c164ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
