<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>delete_Apartment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ffd9a81-d622-447e-b14e-d0fb09e1941e</testSuiteGuid>
   <testCaseLink>
      <guid>bfc38f14-24ad-4fd7-9cbf-783fd00ccbf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/login_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>94a5573e-d50a-4e70-95cb-6e3fe9a0077a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginData/loginSuccess</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>94a5573e-d50a-4e70-95cb-6e3fe9a0077a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>12db6fb3-1f7d-4c3e-b791-410378a03fb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>94a5573e-d50a-4e70-95cb-6e3fe9a0077a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b04ce358-939e-449a-9a4d-5ce21093f005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>94a5573e-d50a-4e70-95cb-6e3fe9a0077a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedMsg</value>
         <variableId>7d9521c1-41c1-4924-978f-4eb62b4df9c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fea46f17-0a5f-4d9e-9c25-0a5945faf89b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/apartment/delete/apartment_delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f8302f-f015-4c4e-9708-a3ab8c0d4a92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>677eeb2c-bec6-4b83-90cd-85ea7443abbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>972fa82d-0393-4cca-bf1a-1983e42892d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d15364e-92cb-4dc2-893d-9940d4123ab0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>532a31a5-b7e3-470a-bcf2-34078f5a98f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cc9156e-18b9-422f-9808-0b06f8ca0d1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a9fbdd0-6b4d-4313-980b-a822b76f6e5f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
