<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectResident</name>
   <tag></tag>
   <elementGuidId>8b46e895-8006-4fa5-a42f-42d48aad9c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#residentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='residentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bdbfcf43-ad71-41df-b279-5dc8d019fa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>cd4bb951-b806-4a2a-ba7b-735318b739d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>fb16e616-2f85-4bf4-bae7-a57dabbe43b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ab83728c-26c6-4e7c-b780-5f286cf44afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>residentName</value>
      <webElementGuid>5879e7db-2b87-4299-baeb-8ffe1c18066b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>Cao Thị T</value>
      <webElementGuid>ba05ae5a-6873-4368-9415-086228441656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh</value>
      <webElementGuid>0c0fcbd1-50b4-4def-9cb9-05b1dd472ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residentName&quot;)</value>
      <webElementGuid>e2fc7baf-c2e5-4e01-afef-0160d3de6b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='residentName']</value>
      <webElementGuid>8942c049-e040-447f-a72f-476b457a6cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/following::select[1]</value>
      <webElementGuid>26d43b64-106c-403c-b5d2-8c7acfabf819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of apartment'])[1]/following::select[2]</value>
      <webElementGuid>cac2f748-8ce5-442c-9bc4-02c3b23aec70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::select[1]</value>
      <webElementGuid>3991028c-7d4c-43cc-866d-ca66d06e0a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number electric'])[1]/preceding::select[1]</value>
      <webElementGuid>202eda90-1331-4714-91bb-e9d162ae2ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bb0f33e8-974e-4b2b-a8c2-12013ad82afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'residentName' and @id = 'residentName' and (text() = 'Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh' or . = 'Select ResidentNguyễn Văn ACao Thị TCao Văn CtuBùi ChiLý VũLê TrangCao DũngHồ BìnhLê Linh')]</value>
      <webElementGuid>dee39a00-5bf7-4797-bfe0-24c52545e390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
