<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectNumOfApart</name>
   <tag></tag>
   <elementGuidId>56a11510-a022-4285-a9f2-3d0eb4a45c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfApartment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='numberOfApartment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cf7cbc4-c2ed-4db8-a0fe-725dcabaf17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>f6e5e277-49ba-49eb-82ba-b8b3a3fd80b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>e72f43b1-a560-4fa8-98c3-6b72c2be54e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e296b1e3-e540-40c4-9975-a748c42ce7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberOfApartment</value>
      <webElementGuid>022ad710-dddf-49fd-a514-9fdb4148520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>202</value>
      <webElementGuid>925d2c9b-a426-41f3-8c28-54043bc67824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Apartment 101  102  711  7  437  436 </value>
      <webElementGuid>0e04bdda-50d1-48da-bbb4-0d9303d16c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfApartment&quot;)</value>
      <webElementGuid>b5e111a7-57e2-4183-bf5b-2d4783b4e8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='numberOfApartment']</value>
      <webElementGuid>ddb7f428-5934-44d7-9641-c65dc51a5ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of apartment'])[1]/following::select[1]</value>
      <webElementGuid>bb14bf53-db77-4897-91b4-b15bba7e68ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Report'])[1]/following::select[1]</value>
      <webElementGuid>961e12d2-ebb2-4eaf-8857-b576aaac6468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident name'])[1]/preceding::select[1]</value>
      <webElementGuid>1f8e39b4-cb14-4ce0-9b6b-b63e3e1d95aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::select[2]</value>
      <webElementGuid>dff41f53-bd7f-43d7-ab18-ee38252371f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5977da8a-832b-4ee0-9a76-851b669c5757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'numberOfApartment' and @id = 'numberOfApartment' and (text() = 'Select Apartment 101  102  711  7  437  436 ' or . = 'Select Apartment 101  102  711  7  437  436 ')]</value>
      <webElementGuid>b4c86c17-72a5-4fa0-accd-f3dcd7ccf82a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
