<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNumberWater</name>
   <tag></tag>
   <elementGuidId>e4438918-d453-4ff4-a1d7-485304dbe244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberWater</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberWater']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f86f2f35-c997-4981-b72d-efc369e31323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca88b1fa-c1b2-496c-8d5a-81c3c48139c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberWater</value>
      <webElementGuid>05454bd8-43bc-41d2-a103-878365446bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>x6000/Liter</value>
      <webElementGuid>511f6969-0014-4e1f-b424-1bf949ccc7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>d8887719-d2e3-4243-bbfb-c35f2715265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberWater</value>
      <webElementGuid>1d618c8d-5b4f-450f-b197-369f36f5060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>036e7873-c689-4afa-800d-62b70cd698f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>df6fe770-d6df-49bc-9328-38f5f0e1e196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberWater</value>
      <webElementGuid>61973d23-402d-4184-bd2e-665ee607c3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f9ff9aef-0783-4f24-899a-96e0f63755d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberWater&quot;)</value>
      <webElementGuid>1f9ff5f6-939b-4154-80a5-ac18d32882c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberWater']</value>
      <webElementGuid>96a2be7d-f621-41e1-a31e-a96b59b92c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>f06643b9-b33f-4f0c-bc9d-9d6cd44b036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'numberWater' and @placeholder = 'x6000/Liter' and @name = 'numberWater']</value>
      <webElementGuid>32c22309-020b-40e9-b2f2-8266287d7d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
