<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNumberElec</name>
   <tag></tag>
   <elementGuidId>ebf54890-8010-4e7f-8e5f-d3db32386bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberElectric</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberElectric']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b875de0-201e-43c8-8700-da039e1a8105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2f8c41c-5baf-408d-ade4-3e1e2ba3f181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>ddc6f575-0cb2-4c8f-b603-185e218a1f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>x3500/Volt</value>
      <webElementGuid>a254ad34-d5f8-446a-9e78-5c1d78c5a305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>1d0f055d-8e3f-42e7-8aa2-0cbd6e56b4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>7ece0367-b766-4811-85e1-72d175485796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9f9e69f3-8a37-4ebf-bcf7-357f0b633421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>b3f19382-1a7e-43a7-b62d-cec67ac3f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>numberElectric</value>
      <webElementGuid>03e937fd-9539-4b42-9cf6-e50680d30ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c6043afc-ff66-42ba-86ee-9c7e6bd7294e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberElectric&quot;)</value>
      <webElementGuid>cacaa0c1-4648-4fd4-8938-ac6bfa6251cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberElectric']</value>
      <webElementGuid>c01e646f-e4dd-4375-af15-c467f0cc656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e5c774f3-f7c5-48b4-bd87-985b6001a310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'numberElectric' and @placeholder = 'x3500/Volt' and @name = 'numberElectric']</value>
      <webElementGuid>85959ee6-39ba-4cd1-90ab-8586f80d7203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
