<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtToiletMoney</name>
   <tag></tag>
   <elementGuidId>f76a9bc8-616b-46e9-9119-3f773c78e94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toiletMoney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='toiletMoney']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8405b172-4908-4c14-bbcf-690b91e0c06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08def8f0-12b0-44bc-9780-25ff33a15149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>0987285b-563b-4000-8c3b-a7f51a953931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>527206d4-9aed-4ccc-97c5-c6d370e0fbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>26957da3-fef3-488f-a5b7-d5f1569c9d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3b1f4b1d-e09f-455f-90e5-d4ac6b60ad85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[0-9]+$</value>
      <webElementGuid>5f77fa82-369a-4eb9-8063-5b1b383ca31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>toiletMoney</value>
      <webElementGuid>26f0cd61-0091-494e-9859-2ebd5a304206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>20000</value>
      <webElementGuid>f58f2cb6-dcfd-42dc-a36f-7abf47ccf319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toiletMoney&quot;)</value>
      <webElementGuid>e9e7a9af-65d0-458a-876c-c3f51ccb0d2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='toiletMoney']</value>
      <webElementGuid>b0000313-5a2b-46d5-aade-885d2a9c08f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>6666adde-704b-410e-9534-3af41456daa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'toiletMoney' and @name = 'toiletMoney']</value>
      <webElementGuid>71fbeb25-dfc6-4bf5-b773-d49d05948039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
